theme: jekyll-theme-cayman
title: "CSOR2019: Relational Databases And Their Use"
description: "Slides and resources for the database part of the course "Computational Statistics & Operations Research", Aalborg University, spring 2019"
show_downloads: false
